service:
  name: cors

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-domain-manager
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  memorySize: 256
  environment:
    stage: ${opt:stage, self:provider.stage}

functions:
  get:
    handler: handler.get
    events:
      - http:
          method: get
          path: /
          cors:
            origins:
              - *.banyudu.com
            headers:
              - Content-Type
              - X-Amz-Date
              - Authorization
              - X-Api-Key
              - X-Amz-Security-Token
              - X-Amz-User-Agent
            allowCredentials: false

custom:
  domains:
    prod: api.banyudu.com
    staging: staging-api.banyudu.com
    dev: dev-api.banyudu.com

  customDomain:
    domainName: ${self:custom.domains.${self:provider.environment.stage}} # Change this to your domain.
    basePath: 'cors' # This will be prefixed to all routes
    stage: ${self:provider.environment.stage}
    createRoute53Record: true